contador = 100
"""INICIALIZAMOS CONTADOR EN 100, LUEGO COMPROBAMOS QUE SEA IGUAL O MENOR QUE 100
UNA VEZ SEA VALIDADO(TRUE) INGRESA AL BUCLE E IMPRIME CONTADOR, LUEGO INDICAMOS
QUE CONTADOR ES IGUAL A CONTADOR -1 Y POR ÚLTIMO, AGREGAMOS UN CONDICIONAL
QUE COMPRUEBE QUE SEA CONTADOR == 0 (PARA QUE NO SEA UN BUCLE INFINITO)
UNA VEZ COMPROBADO ROMPEMOS EL BUCLE CON BREAK.
"""
while contador <= 100:
    print(contador)
    contador -=1
    if contador == 0:
        break